name: ${project.artifactId}
main: ${project.groupId}.bukkit.FactAchivementsBukkit
version: ${project.version}
authors: [TrollyLoki, Arti_Creep]

depend: [FactCore]

api-version: 1.14

commands:
  factachivements:
    aliases: [factachive, fa]
    permission: factachivements.manage